{% set name = "azure-mgmt-privatedns" %}
{% set version = "1.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: b60f16e43f7b291582c5f57bae1b083096d8303e9d9958e2c29227a55cc27c45

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - setuptools
    - wheel
    - python
    - pip
  run:
    - python
    - msrest >=0.5.0
    - azure-mgmt-core >=1.2.0,<2.0.0
    - azure-common >=1.1,<2

test:
  imports:
    - azure.mgmt.privatedns
    - azure.mgmt.privatedns.aio
  commands:
    - pip check
  requires:
    - pip

about: 
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure DNS Private Zones Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: Microsoft Azure DNS Private Zones Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://github.com/Azure/azure-sdk-for-python
  
